extends:
  - eslint:recommended
env:
  browser: true
  es6: true
  node: true
ecmaFeatures:
  arrowFunctions: true
  blockBindings: true
  classes: true
  defaultParams: true
  destructuring: true
  forOf: true
  generators: true
  modules: true
  spread: true
  templateStrings: true
  jsx: true
rules:
  react/no-multi-comp: off
  react/jsx-indent-props: [2, 4]
  object-curly-spacing: ["error", "never"]
  object-shorthand: off
  no-unused-vars: ["error", {"argsIgnorePattern": "_$"}]
  indent: ["off", 4, {"VariableDeclarator": {"var": 2, "let": 2, "const": 1}}]
  quotes: [0]
  key-spacing: [0]
  new-cap: [0]
  no-multi-spaces: [0]
  no-shadow: [0]
  no-use-before-define: [2, "nofunc"]
  eqeqeq: [1]
  comma-dangle: ["error", "never"]
  space-before-function-paren: ["error", "never"]
plugins:
  - react
